### ISSUE TITLE
Human-readable error message when parsing the JSON-config fails

### ISSUE THREAD

**Issue by MatthiasZepper** [ScilifelabDataCentre/dds_cli#149]
Since end users will likely be using the JSON config files, maybe it is desirable to catch JSON parsing errors and print a human-readable error message instead? 

I was using this `.dds-cli.json` (_Password and username redacted_)

```
{
“username” : “...” ,
“password”:  “...” 
}
```

Placing this file in my user directory resulted in this lengthy error:

```
ERROR    <traceback object at 0x108768040>                                                                                                                     exceptions.py:48
         Traceback (most recent call last):                                                                                                                                    
           File "/Users/matthias.zepper/Documents/Coding/Python/DDS-cli/dds_cli/file_handler.py", line 75, in extract_config                                                   
             contents = json.load(cfp)                                                                                                                                         
           File "/opt/homebrew/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 293, in load                             
             return loads(fp.read(),                                                                                                                                           
           File "/opt/homebrew/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads                            
             return _default_decoder.decode(s)                                                                                                                                 
           File "/opt/homebrew/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode                            
             obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                                                                                 
           File "/opt/homebrew/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 353, in raw_decode                        
             obj, end = self.scan_once(s, idx)                                                                                                                                 
         json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)                                                             
Traceback (most recent call last):
  File "/Users/matthias.zepper/Documents/Coding/Python/DDS-cli/dds_cli/file_handler.py", line 75, in extract_config
    contents = json.load(cfp)
  File "/opt/homebrew/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/opt/homebrew/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/dds", line 33, in <module>
    sys.exit(load_entry_point('dds-cli', 'console_scripts', 'dds')())
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/matthias.zepper/Documents/Coding/Python/DDS-cli/dds_cli/__main__.py", line 271, in ls
    with dds_cli.data_lister.DataLister(
  File "/Users/matthias.zepper/Documents/Coding/Python/DDS-cli/dds_cli/data_lister.py", line 60, in __init__
    super().__init__(username=username, config=config, project=project, method=method)
  File "/Users/matthias.zepper/Documents/Coding/Python/DDS-cli/dds_cli/base.py", line 75, in __init__
    username, password, self.project = self.__verify_input(
  File "/Users/matthias.zepper/Documents/Coding/Python/DDS-cli/dds_cli/base.py", line 129, in __verify_input
    contents = fh.FileHandler.extract_config(configfile=config)
  File "/Users/matthias.zepper/Documents/Coding/Python/DDS-cli/dds_cli/file_handler.py", line 77, in extract_config
    raise dds_cli.exceptions.ConfigFileExtractionError(
dds_cli.exceptions.ConfigFileExtractionError: Could not extract info from config file: /Users/matthias.zepper/.dds-cli.json
```
Thanks!

**Comment by inaod568** [comment]
Yes, there should be a better error message. I will put this in minor tasks. 👍🏻 

I see that there are spaces in the file where there shouldn't be (if you haven't already seen that? Or maybe it was intentional?) so that's probably why it's raising the error. It's also possible that there is missing indentation. Try: 
```
{
“username”: “...”,
“password”: “...” 
}
```
or 
```
{
    “username”: “...”,
    “password”: “...”
}

```

**Comment by ewels** [comment]
Could also be the fancy quotes? I would run the file contents through a JSON validator if in doubt. I don't _think_ the whitespace should matter 🤔

**Comment by ewels** [comment]
_PROTIP:_ If you use the GitHub markdown syntax highlighting for fenced code blocks, it shows that the snippet is invalid:

```json
{
“username” : “...” ,
“password”:  “...” 
}
```

Then if I replace the quotes:

```json
{
"username" : "..." ,
"password":  "..." 
}
```

**Comment by inaod568** [comment]
> Could also be the fancy quotes? I would run the file contents through a [JSON validator](https://jsonformatter.curiousconcept.com/) if in doubt. I don't _think_ the whitespace should matter 🤔

True!

**Comment by inaod568** [comment]
> _PROTIP:_ If you use the GitHub markdown syntax highlighting for fenced code blocks, it shows that the snippet is invalid:
> 
> ```json
> {
> “username” : “...” ,
> “password”:  “...” 
> }
> ```
> 
> Then if I replace the quotes:
> 
> ```json
> {
> "username" : "..." ,
> "password":  "..." 
> }
> ```

Ah, good tip, thanks!

**Comment by MatthiasZepper** [comment]
Oh, I actually didn't bother too much about what was actually wrong with the JSON and just entered the parameters instead. But now that Phil found out, I noticed that it actually _did_ print a meaningful error message hidden between all the other stuff: 

``json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
``

Thanks for digging so deep into this and also the helpful suggestion with the markdown syntax highlighting!
