### ISSUE TITLE
`--usage` flag is broken on `dds ls` respectively `dds project ls`

### ISSUE THREAD

**Issue by MatthiasZepper** [ScilifelabDataCentre/dds_cli#223]
**BUG**

Possibly by moving the project out of the JSON and into the request.args (#220) the `dds ls --usage` command is broken. The error seems to occur in the function that does the formatting to SI prefixed units (kB or GB and such):

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/dds", line 33, in <module>
    sys.exit(load_entry_point('dds-cli', 'console_scripts', 'dds')())
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/matthias.zepper/Documents/Coding/Python/dds_cli/dds_cli/__main__.py", line 522, in list_projects
    ctx.invoke(ls, username=username, json=json, sort=sort, usage=usage)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/matthias.zepper/Documents/Coding/Python/dds_cli/dds_cli/__main__.py", line 165, in ls
    projects = lister.list_projects(sort_by=sort)
  File "/Users/matthias.zepper/Documents/Coding/Python/dds_cli/dds_cli/data_lister.py", line 118, in list_projects
    self.__print_project_table(sorted_projects, usage_info, total_size)
  File "/Users/matthias.zepper/Documents/Coding/Python/dds_cli/dds_cli/data_lister.py", line 548, in __print_project_table
    magnitudes = dds_cli.utils.calculate_magnitude(sorted_projects, column_formatting.keys())
  File "/Users/matthias.zepper/Documents/Coding/Python/dds_cli/dds_cli/utils.py", line 38, in calculate_magnitude
    values = [proj[key] for proj in projects]
  File "/Users/matthias.zepper/Documents/Coding/Python/dds_cli/dds_cli/utils.py", line 38, in <listcomp>
    values = [proj[key] for proj in projects]
```

**COULD HAVE**

While investigating the bug to see if it is a CLI or a WEB issue, I also realized that 

`dds project ls --json --usage`

does not return the usage in the JSON. This might also be an useful feature?

**Comment by MatthiasZepper** [comment]
Because it turned out to be an issue with the API response, [PR#778](https://github.com/ScilifelabDataCentre/dds_web/pull/778) will fix both - the bug and the optional feature that we already had but that was not working as well.

**Comment by MatthiasZepper** [comment]
Fixed with [PR778 of the API](https://github.com/ScilifelabDataCentre/dds_web/pull/778)
