### ISSUE TITLE
`dds user delete --self` broken

### ISSUE THREAD

**Issue by alneberg** [ScilifelabDataCentre/dds_cli#348]
```
root@2e8c483dd141:/code# dds user delete --self
     ︵
 ︵ (  )   ︵
(  ) ) (  (  )   SciLifeLab Data Delivery System
 ︶  (  ) ) (    https://delivery.scilifelab.se/
      ︶ (  )    Version 0.0.10
          ︶
Current user: unituser_1
Are you sure? Deleted accounts can't be restored! [y/n]: y
Traceback (most recent call last):
  File "/usr/local/bin/dds", line 33, in <module>
    sys.exit(load_entry_point('dds-cli', 'console_scripts', 'dds')())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rich_click/rich_click.py", line 594, in main
    return super().main(*args, standalone_mode=False, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/code/dds_cli/__main__.py", line 491, in delete_user
    manager.delete_own_account()
  File "/code/dds_cli/account_manager.py", line 135, in delete_own_account
    dds_cli.auth.Auth.logout()
TypeError: Auth.logout() missing 1 required positional argument: 'self'
```

Should be fairly easy to fix.

**Comment by inaod568** [comment]
Solved in #352
