### ISSUE TITLE
Error when combining options for `data ls`

### ISSUE THREAD

**Issue by nylander** [ScilifelabDataCentre/dds_cli#652]
Hi!

I'm encountering errors while attempting to combine both `--tree` and `--size` as arguments to `data ls` (error output below). 

Having the combined information could be very useful (just as in shell command `tree -sh`).

If the combination of arguments are not intended, the code should probably want to catch and handle those user cases appropriately.

Thanks /Johan

## Error output

```
$ dds_cli data ls --tree --size --project x
     ︵ 
 ︵ (  )   ︵ 
(  ) ) (  (  )   SciLifeLab Data Delivery System 
 ︶  (  ) ) (    https://delivery.scilifelab.se/ 
      ︶ (  )    CLI Version 2.5.0 
          ︶
Current user: x
Traceback (most recent call last):
  File "dds_cli/__init__.py", line 183, in <module>
  File "click/core.py", line 1130, in __call__
  File "rich_click/rich_group.py", line 21, in main
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "click/decorators.py", line 26, in new_func
  File "dds_cli/__main__.py", line 1823, in list_data
  File "click/core.py", line 760, in invoke
  File "click/decorators.py", line 38, in new_func
  File "dds_cli/__main__.py", line 288, in list_projects_and_contents
  File "dds_cli/data_lister.py", line 371, in list_recursive
  File "dds_cli/data_lister.py", line 269, in __construct_file_tree
  File "dds_cli/data_lister.py", line 271, in <genexpr>
AttributeError: 'float' object has no attribute 'split'
[1482969] Failed to execute script '__init__' due to unhandled exception!

```

## dds_cli and system info
```
$ dds --version
     ︵ 
 ︵ (  )   ︵ 
(  ) ) (  (  )   SciLifeLab Data Delivery System 
 ︶  (  ) ) (    https://delivery.scilifelab.se/ 
      ︶ (  )    CLI Version 2.5.0 

$ ldd $(which dds_cli)
        linux-vdso.so.1 (0x00007fffac908000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd4810c1000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fd4810a5000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd481082000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd480e90000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fd4810d1000)

$ python -V
Python 3.8.10

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

```

**Comment by i-oden** [comment]
Hi! Thanks for this bug report. We'll look into this!
